# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

name: better-start

services:
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:${LIBSQL_VERSION:-latest}
    hostname: libsql
    ports:
      - 5001:5001 # gRPC connection
      - 8080:8080 # user HTTP connection
      - 8081:8081 # admin HTTP connection
    volumes:
      - libsql_data:/var/lib/sqld/data:rw
    command: '/bin/sqld --enable-namespaces --enable-http-console --max-active-namespaces 2000'

volumes:
  libsql_data:
    driver: local
